### ISSUE TITLE
Error executing job: E/JobRescheduleService: Not allowed to start service Intent

### ISSUE THREAD

**Issue by wemrekurt** [jamesisaac/react-native-background-task#61]
Log output:
```
10-15 21:06:41.832 3794-15881/? W/ActivityManager: Background start not allowed: service Intent { cmp=hr.apps.n206998169/com.evernote.android.job.JobRescheduleService (has extras) } to hr.apps.n206998169/com.evernote.android.job.JobRescheduleService from pid=22269 uid=10618 pkg=hr.apps.n206998169
10-15 21:06:41.846 22269-22269/hr.apps.n206998169 E/JobRescheduleService: Not allowed to start service Intent { cmp=hr.apps.n206998169/com.evernote.android.job.JobRescheduleService (has extras) }: app is in background uid UidRecord{98f2285 u0a618 TRNB idle procs:1 seq(0,0,0)}
                                                                          java.lang.IllegalStateException: Not allowed to start service Intent { cmp=hr.apps.n206998169/com.evernote.android.job.JobRescheduleService (has extras) }: app is in background uid UidRecord{98f2285 u0a618 TRNB idle procs:1 seq(0,0,0)}
                                                                              at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1538)
                                                                              at android.app.ContextImpl.startService(ContextImpl.java:1484)
                                                                              at android.content.ContextWrapper.startService(ContextWrapper.java:663)
                                                                              at com.evernote.android.job.WakeLockUtil.startWakefulService(WakeLockUtil.java:95)
                                                                              at com.evernote.android.job.JobRescheduleService.startService(JobRescheduleService.java:27)
                                                                              at com.evernote.android.job.JobManager.<init>(JobManager.java:189)
                                                                              at com.evernote.android.job.JobManager.create(JobManager.java:107)
                                                                              at com.jamesisaac.rnbackgroundtask.BackgroundTaskPackage.useContext(BackgroundTaskPackage.java:20)
                                                                              at hr.apps.n206998169.MainApplication.onCreate(MainApplication.java:60)
                                                                              at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1125)
                                                                              at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6056)
                                                                              at android.app.ActivityThread.-wrap1(Unknown Source:0)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                              at android.os.Looper.loop(Looper.java:164)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6938)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
10-15 21:06:41.945 21433-21443/? I/zygote64: Background concurrent copying GC freed 64890(5MB) AllocSpace objects, 16(320KB) LOS objects, 57% free, 4MB/10MB, paused 3.557ms total 112.243ms
10-15 21:06:41.960 22269-22295/hr.apps.n206998169 D/BackgroundTask: Job is running
10-15 21:06:41.970 3794-15881/? W/ActivityManager: Background start not allowed: service Intent { cmp=hr.apps.n206998169/com.jamesisaac.rnbackgroundtask.HeadlessTaskService (has extras) } to hr.apps.n206998169/com.jamesisaac.rnbackgroundtask.HeadlessTaskService from pid=22269 uid=10618 pkg=hr.apps.n206998169
```

```
compileSdkVersion 23
buildToolsVersion "23.0.1"
minSdkVersion 16
targetSdkVersion 26
"react-native": "0.55.3",
```

**Comment by NarendraSingh88** [comment]
I am facing the same.
```
compileSdkVersion 28
buildToolsVersion "28.0.3"
minSdkVersion 16
targetSdkVersion 28
"react-native": "0.59.3",
```

Any luck with this issue @jamesisaac @wemrekurt?
