### ISSUE TITLE
Failure on Android 9

### ISSUE THREAD

**Issue by denchp** [jamesisaac/react-native-background-task#67]
react-native version: 0.58
react-native-background-task: 0.2.1
Android: 9 (API 28)

Error message:
```
2019-02-11 16:22:48.235 5914-16738/com.mobile E/JobExecutor: Crashed job{id=1, finished=true, result=FAILURE, canceled=false, periodic=true, class=RNJob, tag=rnbgtask}
    java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.mobile/com.jamesisaac.rnbackgroundtask.HeadlessTaskService (has extras) }: app is in background uid UidRecord{f5d8d2e u0a229 TRNB bg:+7m30s90ms idle change:uncached procs:1 seq(55,55,55)}
        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1577)
        at android.app.ContextImpl.startService(ContextImpl.java:1532)
        at android.content.ContextWrapper.startService(ContextWrapper.java:664)
        at com.jamesisaac.rnbackgroundtask.RNJob.onRunJob(RNJob.java:35)
        at com.evernote.android.job.Job.runJob(Job.java:123)
        at com.evernote.android.job.JobExecutor$JobCallable.runJob(JobExecutor.java:165)
        at com.evernote.android.job.JobExecutor$JobCallable.call(JobExecutor.java:150)
        at com.evernote.android.job.JobExecutor$JobCallable.call(JobExecutor.java:133)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by marcos93net** [comment]
It also doesn't work on Android 9 here. Did you get it solved?
